### ISSUE TITLE
How to use it? 

### ISSUE THREAD

**Issue by 72sm66** [TrollSkull/SMSBOX#2]
![Screenshot_20231031-203032](https://github.com/TrollSkull/SMSBOX/assets/127276909/a15189f7-2346-4879-8d5d-4427d7f8b524)
how to use it in termux ? When i send any sms its says couldn't send message ! 'quotaRemaining'. Why . Please describe me 😭

**Comment by TrollSkull** [comment]
Hi @72sm66,

This error is because the TextBelt API offers a free daily message, the error is because you no longer have messages available to send due to the free plan!

If you like, you can buy the paid plan that TextBelt offers with up to 50 messages per day for only $3 and then use your paid key in the script 😉

**Comment by TrollSkull** [comment]
At some point I will release an update fixing a few errors in the script, improving it, and adding some more descriptive messages for these errors.
